server:
  port: 8999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/login/**

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/